public class C11_queryBalance{
    private static String template = ""
        + "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\"\n"
        + "	xmlns:ocs=\"http://ocs.ztesoft.com\">\n"
        + "	<soapenv:Header>\n"
        + "		<AuthHeader xmlns=\"http://ZTEsoft.com/webservices/\">\n"
        + "			<Username>${username}</Username>\n"
        + "			<Password>${password}</Password>\n"
        + "		</AuthHeader>\n"
        + "	</soapenv:Header>\n"
        + "	<soapenv:Body>\n"
        + "		<ocs:doService>\n"
        + "			<ocs:in0>\n"
        + "<![CDATA[\n"
        + "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        + "<zsmart>\n"
        + "	<Data>\n"
        + "		<header>\n"
        + "			<ACTION_ID>QueryProfileAndBal</ACTION_ID>\n"
        + "			<REQUEST_ID>${requestID}</REQUEST_ID>\n"
        + "		</header>\n"
        + "		<body>\n"
        + "			<MSISDN>${msisdn}</MSISDN>\n"
        + "			<TransactionSN>${transactionSN}</TransactionSN>\n"
        + "			<UserPwd></UserPwd>\n"
        + "		</body>\n"
        + "	</Data>\n"
        + "</zsmart>\n"
        + "]]>\n"
        + "			</ocs:in0>\n"
        + "		</ocs:doService>\n"
        + "	</soapenv:Body>\n"
        + "</soapenv:Envelope>\n";
}
